### ISSUE TITLE
"HTML format" string must null terminated

### ISSUE THREAD

**Issue by kkzk** [AceofSpades5757/clipboard-win-html#1]
hello.

I tried using the code.
In my environment, it seems that there is a high probability that the copy will fail because there is no NULL at the end of the string used in the format name.

I'm glad if you can use it as a reference.

**Comment by AceofSpades5757** [comment]
Ah, I think I see it. Looks like I didn't use a c string when registering the format.

**Comment by AceofSpades5757** [comment]
@kkzk  Thanks again. Should be all good.
